"""
Django settings for Orchestrator project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os,json
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
settings = json.loads(open(BASE_DIR+'/settings.json').read())
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings['DEBUG']

ALLOWED_HOSTS = settings['ALLOWED_HOSTS']
# Application definition
INSTALLED_APPS = settings['INSTALLED_APPS']

MIDDLEWARE = settings['MIDDLEWARE']
ROOT_URLCONF = settings['ROOT_URLCONF']

TEMPLATES = settings['TEMPLATES']

WSGI_APPLICATION = settings['WSGI_APPLICATION']

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = settings['AUTH_PASSWORD_VALIDATORS']

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = settings['LANGUAGE_CODE']
TIME_ZONE = settings['TIME_ZONE']
USE_I18N = settings['USE_I18N']
USE_L10N = settings['USE_L10N']
USE_TZ = settings['USE_TZ']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = settings['STATIC_URL']

BROKER_URL = settings['BROKER_URL']
CELERY_BROKER_URL = BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

### EMAIL SETTINGS ###
EMAIL_BACKEND = settings['EMAIL']['BACKEND']
EMAIL_USE_TLS = settings['EMAIL']['USE_TLS']
EMAIL_HOST = settings['EMAIL']['HOST']
EMAIL_HOST_USER = settings['EMAIL']['HOST_USER']
EMAIL_HOST_PASSWORD = settings['EMAIL']['HOST_PASSWORD']
EMAIL_PORT = settings['EMAIL']['PORT']